[
  {
    id: 0,
    name: "Class 1",
    schedule: {
      Monday: [
        "English",
        "Biology",
        "Physics",
        "SST",
        "Games",
        "Hindi",
        "Math",
        "Chemistry",
      ],
      Tuesday: [
        "Biology",
        "Games",
        "Physics",
        "Hindi",
        "Chemistry",
        "English",
        "SST",
        "Math",
      ],
      Wednesday: [
        "Physics",
        "SST",
        "Chemistry",
        "English",
        "Hindi",
        "Biology",
        "Games",
        "Math",
      ],
      Thursday: [
        "Biology",
        "SST",
        "Physics",
        "English",
        "Games",
        "Hindi",
        "Math",
        "Chemistry",
      ],
      Friday: [
        "Math",
        "Biology",
        "Hindi",
        "English",
        "Games",
        "SST",
        "Physics",
        "Chemistry",
      ],
      Saturday: [
        "Math",
        "Physics",
        "Biology",
        "Chemistry",
        "English",
        "Hindi",
        "Games",
        "SST",
      ],
      undefined: [],
    },
  },
];
