[
  {
    class: 1,
    schedule: {
      Monday: [
        "Hindi",
        "English",
        "Geography",
        "Games",
        "Geography",
        "PoliticalScience",
        "History",
        "Physics",
      ],
      Tuesday: [
        "Physics",
        "Games",
        "Maths",
        "Economics",
        "Physics",
        "PoliticalScience",
        "Biology",
        "Chemistry",
      ],
      Wednesday: [
        "Physics",
        "Physics",
        "PoliticalScience",
        "Hindi",
        "English",
        "Geography",
        "Physics",
        "Geography",
      ],
      Thursday: [
        "Geography",
        "Physics",
        "PoliticalScience",
        "Economics",
        "English",
        "Hindi",
        "Geography",
        "Biology",
      ],
      Friday: [
        "Biology",
        "Geography",
        "Maths",
        "Games",
        "Maths",
        "Maths",
        "PoliticalScience",
        "Maths",
      ],
      Saturday: [
        "Chemistry",
        "Economics",
        "History",
        "Games",
        "Maths",
        "Biology",
        "PoliticalScience",
        "Hindi",
      ],
    },
  },
  {
    class: 2,
    schedule: {
      Monday: [
        "History",
        "Biology",
        "PoliticalScience",
        "Economics",
        "Chemistry",
        "Games",
        "Biology",
        "History",
      ],
      Tuesday: [
        "PoliticalScience",
        "Biology",
        "English",
        "Physics",
        "Games",
        "Hindi",
        "English",
        "PoliticalScience",
      ],
      Wednesday: [
        "Maths",
        "PoliticalScience",
        "Hindi",
        "English",
        "Biology",
        "Games",
        "Biology",
        "PoliticalScience",
      ],
      Thursday: [
        "Maths",
        "Biology",
        "Physics",
        "History",
        "PoliticalScience",
        "Geography",
        "Hindi",
        "Chemistry",
      ],
      Friday: [
        "History",
        "Hindi",
        "Economics",
        "Geography",
        "Biology",
        "Chemistry",
        "Chemistry",
        "Physics",
      ],
      Saturday: [
        "Hindi",
        "Chemistry",
        "PoliticalScience",
        "English",
        "PoliticalScience",
        "Hindi",
        "Geography",
        "Physics",
      ],
    },
  },
  {
    class: 3,
    schedule: {
      Monday: [
        "English",
        "Maths",
        "Games",
        "Maths",
        "Biology",
        "History",
        "Physics",
        "Economics",
      ],
      Tuesday: [
        "Chemistry",
        "Economics",
        "Physics",
        "English",
        "Hindi",
        "Games",
        "History",
        "Hindi",
      ],
      Wednesday: [
        "Hindi",
        "English",
        "Hindi",
        "Biology",
        "Economics",
        "Physics",
        "Geography",
        "Maths",
      ],
      Thursday: [
        "PoliticalScience",
        "English",
        "History",
        "Economics",
        "Biology",
        "Games",
        "Hindi",
        "Geography",
      ],
      Friday: [
        "Maths",
        "Economics",
        "Chemistry",
        "History",
        "Economics",
        "Geography",
        "Physics",
        "Hindi",
      ],
      Saturday: [
        "PoliticalScience",
        "Hindi",
        "Geography",
        "English",
        "Biology",
        "Geography",
        "PoliticalScience",
        "Physics",
      ],
    },
  },
  {
    class: 4,
    schedule: {
      Monday: [
        "Geography",
        "Chemistry",
        "English",
        "English",
        "Games",
        "History",
        "PoliticalScience",
        "Games",
      ],
      Tuesday: [
        "Hindi",
        "Biology",
        "History",
        "Hindi",
        "English",
        "Chemistry",
        "Hindi",
        "PoliticalScience",
      ],
      Wednesday: [
        "Economics",
        "Geography",
        "Chemistry",
        "Physics",
        "Maths",
        "History",
        "Geography",
        "Games",
      ],
      Thursday: [
        "Physics",
        "Chemistry",
        "Geography",
        "Biology",
        "English",
        "Biology",
        "Physics",
        "PoliticalScience",
      ],
      Friday: [
        "Geography",
        "PoliticalScience",
        "Maths",
        "Maths",
        "PoliticalScience",
        "Physics",
        "Games",
        "Economics",
      ],
      Saturday: [
        "Maths",
        "Physics",
        "English",
        "English",
        "PoliticalScience",
        "Economics",
        "Chemistry",
        "History",
      ],
    },
  },
  {
    class: 5,
    schedule: {
      Monday: [
        "Biology",
        "Hindi",
        "Chemistry",
        "Physics",
        "History",
        "Physics",
        "Geography",
        "Maths",
      ],
      Tuesday: [
        "Physics",
        "Maths",
        "English",
        "Chemistry",
        "Biology",
        "Geography",
        "Physics",
        "Hindi",
      ],
      Wednesday: [
        "History",
        "Chemistry",
        "Hindi",
        "Games",
        "English",
        "English",
        "Games",
        "Biology",
      ],
      Thursday: [
        "English",
        "Geography",
        "Hindi",
        "Chemistry",
        "History",
        "Geography",
        "Biology",
        "Geography",
      ],
      Friday: [
        "Hindi",
        "Physics",
        "Geography",
        "Chemistry",
        "Hindi",
        "English",
        "PoliticalScience",
        "Biology",
      ],
      Saturday: [
        "Geography",
        "Maths",
        "Chemistry",
        "PoliticalScience",
        "English",
        "Hindi",
        "Games",
        "Hindi",
      ],
    },
  },
  {
    class: 6,
    schedule: {
      Monday: [
        "History",
        "Economics",
        "Hindi",
        "PoliticalScience",
        "Hindi",
        "Geography",
        "Hindi",
        "Biology",
      ],
      Tuesday: [
        "Geography",
        "Chemistry",
        "Games",
        "Biology",
        "History",
        "Biology",
        "PoliticalScience",
        "Chemistry",
      ],
      Wednesday: [
        "History",
        "Economics",
        "Physics",
        "Biology",
        "History",
        "Maths",
        "Maths",
        "History",
      ],
      Thursday: [
        "English",
        "History",
        "English",
        "Hindi",
        "Economics",
        "Hindi",
        "Biology",
        "Physics",
      ],
      Friday: [
        "Games",
        "English",
        "Economics",
        "History",
        "Physics",
        "Biology",
        "Geography",
        "Chemistry",
      ],
      Saturday: [
        "Geography",
        "Chemistry",
        "Biology",
        "Biology",
        "Geography",
        "Geography",
        "Hindi",
        "PoliticalScience",
      ],
    },
  },
  {
    class: 7,
    schedule: {
      Monday: [
        "Maths",
        "Biology",
        "Biology",
        "Physics",
        "Geography",
        "Hindi",
        "Games",
        "History",
      ],
      Tuesday: [
        "Physics",
        "Geography",
        "Maths",
        "History",
        "History",
        "Physics",
        "Games",
        "English",
      ],
      Wednesday: [
        "PoliticalScience",
        "Biology",
        "Chemistry",
        "Physics",
        "Hindi",
        "English",
        "Economics",
        "English",
      ],
      Thursday: [
        "Economics",
        "Geography",
        "Games",
        "PoliticalScience",
        "Hindi",
        "Chemistry",
        "Games",
        "Maths",
      ],
      Friday: [
        "PoliticalScience",
        "PoliticalScience",
        "English",
        "Geography",
        "History",
        "Biology",
        "Economics",
        "Geography",
      ],
      Saturday: [
        "Physics",
        "Chemistry",
        "History",
        "Hindi",
        "Games",
        "PoliticalScience",
        "History",
        "Biology",
      ],
    },
  },
  {
    class: 8,
    schedule: {
      Monday: [
        "Physics",
        "Biology",
        "Biology",
        "Biology",
        "Maths",
        "Economics",
        "Economics",
        "Economics",
      ],
      Tuesday: [
        "Economics",
        "Maths",
        "Geography",
        "Geography",
        "History",
        "Hindi",
        "Games",
        "PoliticalScience",
      ],
      Wednesday: [
        "Maths",
        "English",
        "Geography",
        "Economics",
        "Maths",
        "Maths",
        "Geography",
        "Physics",
      ],
      Thursday: [
        "History",
        "Maths",
        "Biology",
        "English",
        "Games",
        "History",
        "Chemistry",
        "Maths",
      ],
      Friday: [
        "Physics",
        "Biology",
        "History",
        "Hindi",
        "Chemistry",
        "Games",
        "English",
        "Geography",
      ],
      Saturday: [
        "Physics",
        "English",
        "Maths",
        "Chemistry",
        "Games",
        "English",
        "Biology",
        "History",
      ],
    },
  },
  {
    class: 9,
    schedule: {
      Monday: [
        "PoliticalScience",
        "Economics",
        "Maths",
        "Economics",
        "Physics",
        "Biology",
        "Games",
        "Geography",
      ],
      Tuesday: [
        "English",
        "Chemistry",
        "Maths",
        "Games",
        "Chemistry",
        "Games",
        "Biology",
        "Geography",
      ],
      Wednesday: [
        "Chemistry",
        "Geography",
        "History",
        "English",
        "History",
        "Games",
        "Chemistry",
        "History",
      ],
      Thursday: [
        "English",
        "Chemistry",
        "Hindi",
        "Geography",
        "Games",
        "Economics",
        "Economics",
        "PoliticalScience",
      ],
      Friday: [
        "Economics",
        "Hindi",
        "Physics",
        "PoliticalScience",
        "Physics",
        "Biology",
        "Maths",
        "English",
      ],
      Saturday: [
        "History",
        "Geography",
        "Chemistry",
        "Physics",
        "Hindi",
        "PoliticalScience",
        "PoliticalScience",
        "English",
      ],
    },
  },
  {
    class: 10,
    schedule: {
      Monday: [
        "Chemistry",
        "Hindi",
        "Physics",
        "Games",
        "Physics",
        "History",
        "Chemistry",
        "PoliticalScience",
      ],
      Tuesday: [
        "Games",
        "Hindi",
        "PoliticalScience",
        "Geography",
        "PoliticalScience",
        "English",
        "Biology",
        "PoliticalScience",
      ],
      Wednesday: [
        "English",
        "Maths",
        "Biology",
        "Geography",
        "Economics",
        "Physics",
        "English",
        "Geography",
      ],
      Thursday: [
        "Economics",
        "Hindi",
        "Physics",
        "Maths",
        "Geography",
        "Games",
        "History",
        "Physics",
      ],
      Friday: [
        "Games",
        "History",
        "Economics",
        "History",
        "Physics",
        "Economics",
        "English",
        "Games",
      ],
      Saturday: [
        "Biology",
        "History",
        "History",
        "Maths",
        "Chemistry",
        "Physics",
        "Economics",
        "Maths",
      ],
    },
  },
];
